version: 2.1

# reusable docker image
docker-image: &docker-image
  docker:
      - image: circleci/node:13.8.0

jobs:

  build:
    <<: *docker-image
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run lint
  
  test:
    <<: *docker-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *docker-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm install # some packages needed update. and other packages needed review (update version from package.json file)
      - run: npm audit fix --force
      - run: npm update postcss --depth 2
      - run: npm update mkdirp --depth 5
      - run: npm update ansi-regex --depth 5 
      - run: npm update loader-utils --depth 2
      - run: npm update ansi-regex --depth 5
      - run: npm update -g ajv --depth 4
      - run: npm update -g eslint 
      - run: npm update -g request --depth 2
      - run: npm update -g qs --depth 3
      - run: npm audit --audit-level=critical


workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test